from typing import List, Optional
from numpy import ndarray

def brute_force_location(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> ndarray: ...

def brute_force_index(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> ndarray: ...

def kd_tree_location(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> ndarray: ...

def kd_tree_index(line_points: ndarray, point_cloud: ndarray, parallel: bool = False) -> ndarray: ...
